// USER
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const CLEAR_UPDATE_USER_INFO = "CLEAR_UPDATE_USER_INFO";


// PRODUCT
export const GET_BEST_SELL_PRODUCTS = "GET_BEST_SELL_PRODUCTS" 
export const GET_NEW_ARRIVAL_PRODUCTS = "GET_NEW_ARRIVAL_PRODUCTS" 
export const GET_BRANDS = "GET_BRANDS" 
export const GET_COLORS = "GET_COLORS" 
export const GET_PRODUCT_TO_DISPLAY = "GET_PRODUCT_TO_DISPLAY"
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const CLEAR_PRODUCT_DETAIL = "CLEAR_PRODUCT_DETAIL"
export const ADD_PRODUCT = "ADD_PRODUCT" 
export const CLEAR_PRODUCT = "CLEAR_PRODUCT" 
export const ADD_BRAND = "ADD_BRAND" 
export const ADD_COLOR = "ADD_COLOR" 
export const ADD_TO_CART_FROM_DETAIL = "ADD_TO_CART_FROM_DETAIL";

// SITE
export const GET_SITE_INFO = 'GET_SITE_INFO'
export const UPDATE_SITE_INFO = 'UPDATE_SITE_INFO'
export const CLEAR_UPDATE_SITE_INFO = 'CLEAR_UPDATE_SITE_INFO'